theme: jekyll-theme-cayman
title: "Neuroflash"
description: "Neuroflash adalah platform berbasis cloud yang memanfaatkan AI untuk menghasilkan flashcard dan kuis adaptif dari dokumen pengguna, guna meningkatkan efektivitas pembelajaran dengan metode yang lebih interaktif, otomatis, dan disesuaikan dengan kebutuhan masing-masing pengguna."
